_wandb:
    value:
        cli_version: 0.21.0
        e:
            qga9mwlmo8ouem9wxtjpukegdoctpi86:
                args:
                    - --dataset
                    - ucihar
                    - --type
                    - channel
                    - --time_mask
                    - "0"
                    - --channel_mask
                    - "1"
                    - --alpha
                    - "0"
                    - --seed
                    - "100"
                    - --epoch
                    - "150"
                codePath: main_wandb.py
                codePathLocal: main_wandb.py
                cpu_count: 14
                cpu_count_logical: 20
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "370211287040"
                        used: "209677709312"
                email: jennyliu080306@gmail.com
                executable: C:\Users\jenny\miniconda3\envs\maskcae\python.exe
                gpu: NVIDIA GeForce RTX 4060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 3072
                      memoryTotal: "8585740288"
                      name: NVIDIA GeForce RTX 4060 Laptop GPU
                      uuid: GPU-a1f24472-2edf-aa7c-3dcb-b9f26e54708a
                host: Jennyliu
                memory:
                    total: "16849256448"
                os: Windows-10-10.0.26100-SP0
                program: main_wandb.py
                python: CPython 3.8.20
                root: C:\Users\jenny\OneDrive\Desktop\PythonProject_HAR
                startedAt: "2025-08-16T02:12:54.145981Z"
                writerId: qga9mwlmo8ouem9wxtjpukegdoctpi86
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 13
                - 15
                - 16
            "4": 3.8.20
            "5": 0.21.0
            "8":
                - 3
            "12": 0.21.0
            "13": windows-amd64
alpha:
    value: 0
batch_size:
    value: 256
channel_mask:
    value: 1
d_model:
    value: 128
dataset:
    value: ucihar
dff:
    value: 256
dir:
    value: datasets/sub
epoch:
    value: 150
lr:
    value: 0.001
no_wandb:
    value: false
num_heads:
    value: 4
num_layers:
    value: 3
seed:
    value: 100
time_mask:
    value: 0
type:
    value: channel
wandb_entity:
    value: null
wandb_name:
    value: ucihar_channel_tm0_cm1_a0.0_s100
wandb_project:
    value: har-masking
